trigger:
- '*'

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Install Python'

- script: |  
    python -m pip install --upgrade pip
    pip install pipenv
    pipenv --python 3.8
    pipenv install nose pylint --dev
  displayName: 'Install dependencies'

- script: |  
    pipenv run pylint app
  displayName: 'Lint with pylint'

- script: |  
    pipenv run nosetests
  displayName: 'Test with nose'